services:
  - type: web
    name: entertainment-recommender-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: RAWG_API_KEY
        sync: false
      - key: GOOGLE_BOOKS_API_KEY
        sync: false
      - key: COMICVINE_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
